### ISSUE TITLE
Cannot read header line if first item is quoted

### ISSUE THREAD

**Issue by wtchen** [vslinko/deno-csv#21] opened 2023-06-06 22:24 UTC
Consider the following CSV:

```
"Editorial Category","Program Name","Program URL","Program Description","Program Summary",Keywords,"Opportunity Status","Posted Date","Close Date","Transportation Type","Eligible Applicants","Eligible Activities","Most Recent Annual Program Funding Amount","Annual Award Amount","Cost Sharing or Matching Requirement","Match Waiver","Rural Set-Aside","Tribal Set-Aside","Grant Opportunity ID","Grant Opportunity Link","Links to Additional Information",Office,Agency,"Eligibility Information","Funding Information","Contact Information",Keywords
```

Note the first item `"Editorial Category"`.

When I run the code:

```
const f = await Deno.open(`${Deno.cwd()}/data.csv`);
for await (const obj of readCSVObjects(f)) {
    console.log(obj);
}
```

I get the following error:

```
Error: Unexpected quote in unquoted field (line 1, character 4)
    at CSVReader.parseCycle (https://deno.land/x/csv@v0.8.0/reader.ts:449:17)
    at eventLoopTick (ext:core/01_core.js:182:11)
```

The same error occurs if I change `"Editorial Category"` to `"EditorialCategory"` (with quotes), so it is not a whitespace issue.

But when I change `"Editorial Category"` to `EditorialCategory` (no quotes), it works fine.

**Comment by vslinko** [comment] 2023-08-01 09:12
Hello @wtchen 

Unfortunately, I can't reproduce the problem. Could you please provide more data:
- the file causing the error
- source code that reads the file
- what version of deno is used
- what version of deno-cvs is used

**Comment by akselinurmio** [comment] 2023-08-11 08:26
Hi @vslinko, please see [this Gist](https://gist.github.com/akselinurmio/640f62c443d61dc8d23f81ca528ae655) I created to reproduce the issue.

**Comment by vslinko** [comment] 2023-08-12 15:40
@akselinurmio I have no idea why, but it works.

```
-@-:~qwe/vslinko/deno-csv master* $ wget https://gist.githubusercontent.com/akselinurmio/640f62c443d61dc8d23f81ca528ae655/raw/710af19f47e75788311aac17f0237cf0dcaf7cfd/demo.csv
--2023-08-12 18:39:44--  https://gist.githubusercontent.com/akselinurmio/640f62c443d61dc8d23f81ca528ae655/raw/710af19f47e75788311aac17f0237cf0dcaf7cfd/demo.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 389 [text/plain]
Saving to: ‘demo.csv’

demo.csv                                   100%[=====================================================================================>]     389  --.-KB/s    in 0s

2023-08-12 18:39:44 (12.4 MB/s) - ‘demo.csv’ saved [389/389]

-@-:~qwe/vslinko/deno-csv master* $ deno --version
deno 1.36.1 (release, x86_64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
-@-:~qwe/vslinko/deno-csv master* $ deno run --allow-read test.ts
{
  Type: "Hyperlink",
  Source: "https://example",
  Destination: "https://example",
  "Size (Bytes)": "0",
  "Alt Text": "",
  Anchor: "Example",
  "Status Code": "404",
  Status: "Not Found",
  Follow: "true",
  Target: "_blank",
  Rel: "",
  "Path Type": "Absolute",
  "Link Path": "//body/div[@id='root']/div/div[@id='maincontent']/aside/div/div[2]/div[7]/div[1]/div[1]/a[2]",
  "Link Position": "Aside",
  "Link Origin": "HTML"
}
```

**Comment by vslinko** [comment] 2023-08-12 15:43
Looks like its because of UTF BOM.

```
-@-:~qwe/vslinko/deno-csv master* $ printf '\xEF\xBB\xBF' > with_bom.txt
-@-:~qwe/vslinko/deno-csv master* $ cat demo.csv >> with_bom.txt
-@-:~qwe/vslinko/deno-csv master* $ deno run --allow-read test.ts
Error: Unexpected quote in unquoted field (line 1, character 4)
    at CSVReader.parseCycle (file:///Users/vslinko/Workspace/vslinko/deno-csv/reader.ts:450:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by vslinko** [comment] 2023-08-12 16:04
@akselinurmio Fixed in https://github.com/vslinko/deno-csv/releases/tag/v0.9.1

**Closed as completed by vslinko** 2023-08-12 16:04 UTC
